//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public string cpf { get; set; }
        public string clientName { get; set; }
        public string lastname { get; set; }
        public string adress { get; set; }
        public int number { get; set; }
        public string neighborhood { get; set; }
        public string cellPhone { get; set; }
        public string phone { get; set; }
        public string zipCode { get; set; }
    }
}
